urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'vologda.views.home', name='home'),
    # url(r'^vologda/', include('vologda.foo.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),

    (r'^tinymce/', include('tinymce.urls')),

    url(r'^robots.txt$', 'django.views.static.serve', {'path':"/robots.txt",'document_root': settings.STATIC_ROOT, 'show_indexes': False }),
    url(r'^/?$', 'wlm.views.index_page'),
    url(r'^list/?$', 'wlm.views.list_page'),
    url(r'^list/region/(?P<id>[0-9]+)/?$', 'wlm.views.list_region'),
    url(r'^list/city/(?P<id>[0-9]+)/?$', 'wlm.views.list_city'),
    url(r'^upload/?$', 'wlm.views.upload'),
    url(r'^add/?$', 'wlm.views.add'),
    url(r'^monument/(?P<id>[0-9]+)/?$', 'wlm.views.monument'),
    url(r'^monument/(?P<id>[0-9]+)/photo/?$', 'wlm.views.monument_photo'),
    url(r'^monument/kult/(?P<kult_id>[0-9]+)/?$', 'wlm.views.redirect_by_kult_id'),
    url(r'^monument/edit/(?P<id>\d+)$', 'wlm.views.monument_edit_form'),
    url(r'^voting/?$', 'wlm.views.voting'),
    url(r'^vote/(?P<photo_id>\d+)/(?P<vote>\d+)/?$', 'wlm.views.vote_for_photo'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^ajax/markers/(?P<zoom>\d{1,2})/(?P<x_tile>\d+)/(?P<y_tile>\d+)/(?P<first>\d+)/(?P<last>\d+)$', 'wlm.ajax.get_tile_markers'),
    url(r'^ajax/markerscount/(?P<zoom>\d{1,2})/(?P<x_tile>\d+)/(?P<y_tile>\d+)$', 'wlm.ajax.get_tile_markers_count'),
    url(r'^ajax/markersregion/(?P<region>\d+)$', 'wlm.ajax.get_region_markers'),
    url(r'^ajax/markerscity/(?P<city>\d+)$', 'wlm.ajax.get_city_markers'),
    url(r'^ajax/citiesregion/(?P<region>\d+)$', 'wlm.ajax.get_region_cities'),

    url(r'^doubles$', 'wlm.views.coordinates_doubled'),
    url(r'^doubles/find$', 'wlm.views.monuments_double_coordinates'),
)

house/models.py
# -*- encoding: utf-8 -*-
import os.path

from django.utils.translation import ugettext_lazy as _
from django.db import models

from tinymce import models as tinymce_models


class Region(models.Model):
    ''' Region description. 
    XXX Shoul this be moved to another application ?
    '''
    name = models.CharField(max_length=250, verbose_name=_("Name"))
    coord = models.CharField(max_length=20, verbose_name=_("Coordinates"))

    def __unicode__(self):
        return self.name


class Street(models.Model):
    ''' One street definition
    XXX Is this object required ?
    '''
    STREET_CHOICES = (
        ('S', _("Street")),
        ('L', _("Lane")),
        ('H', _("Highway")),
        ('Q', _("Square")),
        ('E', _("Embankment")),
        ('P', _("Passage")),
        ('A', _("Avenue")),
        ('B', _("Blind alley")),
    )

    name = models.CharField(max_length=250, verbose_name=_("Name"))
    full_name = models.CharField(blank=True, max_length=250, verbose_name=_("Full name"))
    type = models.CharField(max_length=1, blank=True, choices=STREET_CHOICES, default='S', verbose_name=_("Type"))
    description = tinymce_models.HTMLField(blank=True, verbose_name=_("Description"))

    class Meta:
        ordering = ['name',]

    def __unicode__(self):
        return self.name


class House(models.Model):
    ''' Main class for working.
    This one contains complete definition for one building. It's a heart
    for application.
    '''
    STATE_CHOICES = (
        ('R', _("Restored")),
        ('S', _("Satisfactory")),
        ('U', _("Unsatisfactory")),
        ('A', _("Accident")),
    )

    PROTECTION_CHOICES = (
        ('F', _("Federal")),
        ('R', _("Regional")),
        ('L', _("Local")),
        ('D', _("Determined")),
        ('O', _("OPOKN")),
        ('N', _("No")),
    )
    TYPE_CHOICES = (
        ('C', _("Cultural")),
        ('A', _("Architectural")),
        ('H', _("Historical")),
    )
   
    #minimal required fields
    # Geospatial
    region = models.IntegerField(verbose_name = _("Region of RF"))
    city = models.IntegerField(verbose_name = _("City"), blank = True, null = True)
    street = models.IntegerField(verbose_name = _("Street"), blank = True, null = True)
    coord_lon = models.FloatField(max_length=20, blank=True, null=True, verbose_name=_("Longitude"))
    coord_lat = models.FloatField(max_length=20, blank=True, null=True, verbose_name=_("Latitude"))
    
    #Name and address
    name = models.CharField(max_length=250, blank=True, verbose_name=_("Name"))
    name_alt = models.CharField(max_length=250, blank=True, verbose_name=_("Alternative name"))
    address = models.CharField(max_length=250, blank=True, verbose_name=_("Address"))
    
    #Is this building a part of complex?
    complex_root = models.ForeignKey('self', blank = True, null = True, verbose_name = _("Belong to complex"))
    complex = models.BooleanField(default = False, verbose_name = _("Complex"))
    #Additional info, may be helpful during administration...
    extra_info = tinymce_models.HTMLField(blank=True, verbose_name=_("Additional"))
    state = models.CharField(max_length=1, blank=True, choices=STATE_CHOICES, verbose_name=_("State"))
    protection = models.CharField(max_length=1, blank=True, choices=PROTECTION_CHOICES, verbose_name=_("Protection class"))
    type = models.CharField(max_length = 1, choices = TYPE_CHOICES, verbose_name = _("Type class"))
    
    #External link to Wiki
    ruwiki = models.CharField(max_length=250, blank=True, verbose_name=_("Wikipedia article"))
    #External link to kulturnoe-nasledie.ru
    kult_id = models.PositiveIntegerField(blank=True, null=True, verbose_name=_("ID Kulturnoe Nasledie"))
    
    #Mark this true mean "We check all data"
    verified = models.BooleanField(default = False, verbose_name = _("Verified"))
    #End of minimal required fields
    
    def __unicode__(self):
        return "%s, %s" % (self.name, self.address)


class HousePhoto(models.Model):
    def make_upload_folder(instance, filename):
        dir_name, image_name = os.path.split(filename)
        path = u"%d/%s" % (instance.house.pk, image_name)
        return path

    house = models.ForeignKey('House', verbose_name=_("House"))
    #file = YFField(upload_to=make_upload_folder)
    title = models.CharField(max_length=250, blank=True, verbose_name=_("Title"))
    author = models.CharField(max_length=250, blank=True, verbose_name=_("Author"))

    def __unicode__(self):
        return self.title

class HouseEvent(models.Model):
    TYPE_CHOICES = (
        ('P', _("Projected")),
        ('B', _("Builded")),
        ('R', _("Restored")),
        ('D', _("Demolished")),
    )

    house = models.ForeignKey('House', verbose_name=_("House"))
    date = models.CharField(max_length=250, blank=True, verbose_name=_("Date"))
    type = models.CharField(max_length=1, blank=True, choices=TYPE_CHOICES, verbose_name=_("Event type"))
    comment = models.CharField(max_length=250, blank=True, verbose_name=_("Comment"))

    def __unicode__(self):
        return self.date + ' - ' + self.text

templates/house/add.html
{% extends "base.html" %}

{% block head %}
{% endblock %}

{% block title %}Добавить памятник — {% endblock %}

{% block content %}
<form>

<div class="row">
	<div class="span12">
		<fieldset class="form-horizontal">
			<div class="well control-group">
				<label class="control-label" for="p-name">Название:</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="p-name">
				</div>
			</div>
			<div class="well control-group">
				<label class="control-label" for="p-name">Автор:</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="p-name">
				</div>
			</div>
			<div class="well control-group">
				<label class="control-label" for="p-name">Год:</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="p-name">
				</div>
			</div>
			<div class="well control-group">
				<label class="control-label" for="p-file">Текст:</label>
				<div class="controls">
					<textarea class="input-xlarge" id="textarea" rows="3"></textarea>
				</div>
			</div>
			<div class="well control-group">
				<label class="control-label" for="p-file">Изображение:</label>
				<div class="controls">
					<input class="input-file" id="p-file" type="file">
				</div>
			</div>
		</fieldset>
	</div>
</div>

<div class="row">
<div class="span12">
<div class="well">
	<div class="span2">
		<div class="btn-group">
			<a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
				Регион
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
			{% for region in regions %}
				<li><a href="#" data-id="{{ region.id }}" data-coord="{{ region.long }},{{ region.lat }}">{{ region.name }}</a></li>
			{% endfor %}
			</ul>
		</div>
		<br />
		<div class="btn-group">
			<a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
				Город
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
			{% for region in regions %}
				<li><a href="#" data-id="{{ region.id }}" data-coord="{{ region.long }},{{ region.lat }}">{{ region.name }}</a></li>
			{% endfor %}
			</ul>
		</div>
		<br />
		<div class="btn-group">
			<a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
				Улица
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
			{% for region in regions %}
				<li><a href="#" data-id="{{ region.id }}" data-coord="{{ region.long }},{{ region.lat }}">{{ region.name }}</a></li>
			{% endfor %}
			</ul>
		</div>
	</div>

	<div class="span9">
		<div class="controls">
			<div class="input-append">
				<input class="span7" id="appendedInputButtons" size="16" type="text"><button class="btn pull-right" type="button"><i class="icon-search"></i> Найти памятник</button>
			</div>
		</div>

		<div id="map" class="map map-big"></div>
		<script type="text/javascript">
			var cmUrl = 'http://{s}.tile.cloudmade.com/{{ CMADE_KEY }}/997/256/{z}/{x}/{y}.png';
			var cmAttr = 'карта &copy; OpenStreetMap, рендер &copy; CloudMade';
			var map = new L.Map('map');
			map
				.setView(new L.LatLng(66, 94), 3)
				.addLayer(new L.TileLayer(cmUrl, { maxZoom: 18, attribution: cmAttr }));
			var clusterer = new LeafClusterer(map);

		{% for house in house_list %}
			{% if house.coord_lat %}
				clusterer.addMarker(new L.Marker(new L.LatLng({{ house.coord_lat|stringformat:"f" }}, {{ house.coord_lon|stringformat:"f" }})).bindPopup('<p><a href="/house/{{ house.id }}">{{ house.street.name }}, {{ house.number }}</p>'));
			{% endif %}
		{% endfor %}
		</script>
	</div>
	<div style="clear:both"></div>
</div>
</div>
</div>

<div class="row">
	<div class="span12">
		<div class="form-actions">
			<button type="submit" class="btn btn-large btn-primary pull-right">Отправить</button>
		</div>
	</dev>
</div>

</form>
{% endblock %}

templates/house/house.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/content.css" />
<link rel="stylesheet" href="//api.oldvologda.ru/leaflet/leaflet.css" />
<!--[if lte IE 8]><link rel="stylesheet" href="//api.oldvologda.ru/leaflet/leaflet.ie.css" /><![endif]-->
<script src="//api.oldvologda.ru/leaflet/leaflet.js"></script>
{% endblock %}

{% block title %}{{ house.name }} ({{ house.address }}) — {% endblock %}

{%block moderator_menu%}
{%if perms.monument.can_change%}
<li class="pull-right"><a href='/admin/logout/'>Выйти ({{user}})</a></li>
<li class="pull-right"><a href='/house/edit/{{house.id}}'>Редактировать</a></li>
{%endif%}
{%endblock%}

{% block content %}
<div class="row">
	<div id="main">
		<div id="find" class="show-grid">
			<div class="span8">
				<h2>{{ house.name }}</h2>

			{% if house.coord_lon %}
				<div id="map" class="map"></div>
				<script type="text/javascript">
					$(function(){
				        var item = {
				            "id": {{house.id}},
				            "coord_lat": {{house.coord_lat|stringformat:"f"}},
				            "coord_lon": {{house.coord_lon|stringformat:"f"}},
				            "name": "{{house.name|default:'Неизвестно'}}"
				        }
				        WLM.map.init_map('map');
				        WLM.map.setPosition({{ house.coord_lat|stringformat:"f" }}, {{ house.coord_lon|stringformat:"f" }});
				        WLM.map.addMarker(item);
				        WLM.map.setZoom(10);
				    });
				    /*
				    var cmUrl = 'http://{s}.tile.cloudmade.com/{{ CMADE_KEY }}/997/256/{z}/{x}/{y}.png';
					var cmAttr = 'карта &copy; OpenStreetMap, рендер &copy; CloudMade';
					var map = new L.Map('map');
					map
						.setView(new L.LatLng({{ house.coord_lat|stringformat:"f" }}, {{ house.coord_lon|stringformat:"f" }}), 16)
						.addLayer(new L.TileLayer(cmUrl, {maxZoom: 18, attribution: cmAttr}))
						.addLayer(new L.Marker(new L.LatLng({{ house.coord_lat|stringformat:"f" }}, {{ house.coord_lon|stringformat:"f" }})));
					*/
				</script>
			{% endif %}

				<table class="table">
					<tr>
						<th>Регион</th>
						<td><a href="/list/region/{{ house.region.id }}/">{{ house.region.name }}</a></td>
					</tr>

					<tr>
						<th>Город</th>
						<td><a href="/list/city/{{ house.city.id }}/">{{ house.city.name }}</a></td>
					</tr>

					<tr>
						<th>Адрес</th>
						<td>{{ house.address }}</td>
					</tr>

				{% if house.kult_id %}
					<tr>
						<th>На сайте Культурного наследия</th>
						<td><a href="http://kulturnoe-nasledie.ru/monuments.php?id={{ house.kult_id|stringformat:"010d" }}" target="_blank">{{ house.kult_id|stringformat:"010d" }}</a></td>
					</tr>
				{% endif %}

				{% if house.ruwiki %}
					<tr>
						<th>В Википедии</th>
						<td><a href="//ru.wikipedia.org/wiki/{{ house.ruwiki|urlencode }}" target="_blank">{{ house.ruwiki }}</a></td>
					</tr>
				{% endif %}

				{% if house.safety %}
					{% if house.state and house.safety in 'S' %}
					<tr>
						<th>Сохранность и состояние</th>
						<td class="state-{{ house.state }}">{{ house.get_safety_display }} ({{ house.get_state_display|lower }})</td>
					</tr>
					{% else %}
					<tr>
						<th>Сохранность и состояние</th>
						<td class="safety-{{ house.safety }}">{{ house.get_safety_display }}</td>
					</tr>
					{% endif %}
				{% endif %}

				{% if house.protection %}
					<tr>
						<th>Категория охраны</th>
						<td>{{ house.get_protection_display }}</td>
					</tr>
				{% endif %}

				{% if house.material %}
					<tr>
						<th>Тип</th>
						<td>{{ house.get_material_display }}</td>
					</tr>
				{% endif %}

				{% if house.extra_info %}
					<tr>
						<th>Дополнительная информация</th>
						<td>{{ house.extra_info|safe }}</td>
					</tr>
				{% endif %}
				</table>
			</div>
		</div>
	</div>
	{% comment %}
	<div id="about" class="show-grid">
		<div class="span4">
			<div class="upload-block">
				<a class="btn btn-large btn-upload" href="//commons.wikimedia.org/w/index.php?title=Special:UploadWizard&campaign=wlm-ru&uselang=ru&id={{ house.kult_id|stringformat:"010d" }}">
					<i class="upload-my"></i>
					Загрузить фото
				</a>
				<br />
				<small>Необходимо <a href="//commons.wikimedia.org/w/index.php?title=Special:UserLogin&uselang=ru">авторизоваться</a> на Викискладе</small>
			</div>
		</div>
	</div>
	{% endcomment %}
</div>
{% endblock %}

templates/house/index.html
{% extends "base.html" %}

{% block head %}
<script type='text/javascript' src='{{STATIC_URL}}/js/wlm.js'></script>
{% endblock %}

{% block title %}{% endblock %}

{% block content %}
<div class="row">
	<div class="span12">
		<div class="well" style="margin-bottom:0">
			Конкурс завершён. Победители будут объявлены 31 октября.
		</div>
	</div>
</div>
<div class="row">
	<div id="main" class="span9">
		<div id="find" class="row show-grid">
			<div class="span9">
				<div class="content">
					<h2>Найдите памятник</h2>

					<div class="row">
						<div id="boxMap" class="span9">
							<div id="location">
								<p class="title"><i class="icon-screenshot"></i>Введите регион и город вручную</p>
								<div class="controls">
									<label class="control-label" for="filter-region">Выберите регион</label>
									<select id="filter-region" name="region">
										{% for r in regions %}
										<option value='{{r.id}}' {%if r.id = region.id%}selected="selected"{%endif%}>{{r.name}}</option>
										{%endfor%}
									</select>
								</div>
								<div class="controls">
									<label class="control-label" for="filter-city">Выберите город</label>
									<select id="filter-city" name="city">
										<option></option>
									</select>
								</div>
							</div>

							<div id="map" class="map map-big"></div>
							<script type="text/javascript">
								var regions = {
                                        {%for r in regions%}
                                        "{{r.id}}" : {"latitude":{{r.latitude|stringformat:"f"}}, "longitude":{{r.longitude|stringformat:"f"}}, "scale":{{r.scale}} }{%if not r.last%},{%endif%}
                                        {%endfor%}
                                    };
                                $(function(){
                                    var setCities = function(data){
                                        $('#filter-city option:gt(0)').remove();
                                        $.each(data, function(key, value){
                                            $('#filter-city').append($("<option></option>")
                                                .attr("value", value.id)
                                                .text(value.name));
                                        });
                                    }
                                    WLM.map.init_map('map');
                                    WLM.map.regionMarkers($('#filter-region option:selected').val());
                                    WLM.getRegionCities($('option:selected').val(), setCities);
                                    $('#filter-region').change(function(){
                                        WLM.map.regionMarkers($('option:selected', $(this)).val());
                                        WLM.getRegionCities($('option:selected', $(this)).val(), setCities);
                                    });
                                    $('#filter-city').change(function(){
                                        var city = $('option:selected', $(this)).val();
                                        if (city){
                                            WLM.map.cityMarkers(city);
                                        }else{
                                            WLM.map.regionMarkers($('#filter-region option:selected').val());
                                        }
                                    });
                                });
							</script>
						</div>
					</div>
				</div>
			</div>
		</div>

		{% comment %}
		<div id="result">
			<h2>Результаты поиска</h2>
			<div class="content">

				<!-- .element-result -->
				<div id="foto-81" class="element-result">
					<a class="foto-link" href="http://opora.me/alboms/lesnoe-konobeevo/">
						<img height="118" width="169" style="position: absolute;" src="{{ STATIC_URL }}img/fotoFx.png">
						<img height="118" width="169" title="" alt="" class="" src="{{ STATIC_URL }}img/simpleimg.jpg">
					</a>
						<p><a href="#" class="title-link">Фоторафия 1</a></p>
				</div>
				<!-- .element-result -->

				<div id="foto-81" class="element-result">
					<a class="foto-link" href="http://opora.me/alboms/lesnoe-konobeevo/">
						<img height="118" width="169" style="position: absolute;" src="{{ STATIC_URL }}img/fotoFx.png">
						<img height="118" width="169" title="" alt="" class="" src="{{ STATIC_URL }}img/simpleimg.jpg">
					</a>
						<p><a href="#" class="title-link">Фоторафия 1</a></p>
				</div>
				<div id="foto-81" class="element-result">
					<a class="foto-link" href="http://opora.me/alboms/lesnoe-konobeevo/">
						<img height="118" width="169" style="position: absolute;" src="{{ STATIC_URL }}img/fotoFx.png">
						<img height="118" width="169" title="" alt="" class="" src="{{ STATIC_URL }}img/simpleimg.jpg">
					</a>
						<p><a href="#" class="title-link">Фоторафия 1</a></p>
				</div>
				<div id="foto-81" class="element-result">
					<a class="foto-link" href="http://opora.me/alboms/lesnoe-konobeevo/">
						<img height="118" width="169" style="position: absolute;" src="{{ STATIC_URL }}img/fotoFx.png">
						<img height="118" width="169" title="" alt="" class="" src="{{ STATIC_URL }}img/simpleimg.jpg">
					</a>
						<p><a href="#" class="title-link">Фоторафия 1</a></p>
				</div>
				<div id="foto-81" class="element-result">
					<a class="foto-link" href="http://opora.me/alboms/lesnoe-konobeevo/">
						<img height="118" width="169" style="position: absolute;" src="{{ STATIC_URL }}img/fotoFx.png">
						<img height="118" width="169" title="" alt="" class="" src="{{ STATIC_URL }}img/simpleimg.jpg">
					</a>
						<p><a href="#" class="title-link">Фоторафия 1</a></p>
				</div>
				<div id="foto-81" class="element-result">
					<a class="foto-link" href="http://opora.me/alboms/lesnoe-konobeevo/">
						<img height="118" width="169" style="position: absolute;" src="{{ STATIC_URL }}img/fotoFx.png">
						<img height="118" width="169" title="" alt="" class="" src="{{ STATIC_URL }}img/simpleimg.jpg">
					</a>
						<p><a href="#" class="title-link">Фоторафия 1</a></p>
				</div>
				<div style="clear:both;"></div>
			</div>
		</div>
		{% endcomment %}
	</div>

	<div id="about" class="row show-grid">
		<div class="span3">
			<h2>О&nbsp;проекте</h2>
			<div class="content">
				<p>«Вики любит памятники» — часть организуемого региональными отделениями Викимедиа международного фотосоревнования Wiki Loves Monuments`2012, проходящего в&nbsp;сентябре 2012 года.</p>
				<p>В&nbsp;конкурсе участвуют самостоятельно сделанные и в&nbsp;сентябре 2012 года самостоятельно загруженные под свободной лицензией на&nbsp;Викисклад фотографии, на&nbsp;которых запечатлён памятник архитектуры из&nbsp;специального списка.</p>
				<hr />
				<p><i class="icon-warning-sign icon-white"></i> В данный момент часть памятников не&nbsp;показывается на&nbsp;карте. Поэтому, если вы не&nbsp;нашли какого-то памятника, вернитесь через пару дней. Всё будет.</p>
			</div>
		</div>
	</div>

	{% comment %}
	<div id="sidebar" class="span3">
		<h2>Фотографии с наиболее высокими оценками</h2>
		
		<!-- .content -->
		<div class="content">

			<!-- .element-sidebar -->
			<div class="element-sidebar clearfix">
				<img height="39" width="51" src="{{ STATIC_URL }}img/simpleimg.jpg" alt="">
				<div>
					<p class="title"><a href="#">Памятник Пушкину</a></p>
					<p class="rating">Голосов за: 315</p>
				</div>
			</div>
			<!-- /.element-sidebar -->

			<div class="element-sidebar clearfix">
				<img height="39" width="51" src="{{ STATIC_URL }}img/simpleimg.jpg" alt="">
				<div>
					<p class="title"><a href="#">Памятник Пушкину</a></p>
					<p class="rating">Голосов за: 315</p>
				</div>
			</div>
			<div class="element-sidebar clearfix">
				<img height="39" width="51" src="{{ STATIC_URL }}img/simpleimg.jpg" alt="">
				<div>
					<p class="title"><a href="#">Памятник Пушкину</a></p>
					<p class="rating">Голосов за: 315</p>
				</div>
			</div>
			<div class="element-sidebar clearfix">
				<img height="39" width="51" src="{{ STATIC_URL }}img/simpleimg.jpg" alt="">
				<div>
					<p class="title"><a href="#">Памятник Пушкину</a></p>
					<p class="rating">Голосов за: 315</p>
				</div>
			</div>
		</div>
		<!-- /.content -->


		<h2>Фотографии без оценок</h2>
		
		<!-- .content -->
		<div class="content">

			<!-- .element-sidebar -->
			<div class="element-sidebar clearfix">
				<img height="39" width="51" src="{{ STATIC_URL }}img/simpleimg.jpg" alt="">
				<div>
					<p class="title"><a href="#">Памятник Пушкину</a></p>
					<p class="rating"></p>
				</div>
			</div>
			<!-- /.element-sidebar -->

			<div class="element-sidebar clearfix">
				<img height="39" width="51" src="{{ STATIC_URL }}img/simpleimg.jpg" alt="">
				<div>
					<p class="title"><a href="#">Памятник Пушкину</a></p>
					<p class="rating"></p>
				</div>
			</div>
			<div class="element-sidebar clearfix">
				<img height="39" width="51" src="{{ STATIC_URL }}img/simpleimg.jpg" alt="">
				<div>
					<p class="title"><a href="#">Памятник Пушкину</a></p>
					<p class="rating"></p>
				</div>
			</div>
			<div class="element-sidebar clearfix">
				<img height="39" width="51" src="{{ STATIC_URL }}img/simpleimg.jpg" alt="">
				<div>
					<p class="title"><a href="#">Памятник Пушкину</a></p>
					<p class="rating"></p>
				</div>
			</div>
		</div>
	</div>
	{% endcomment %}
</div>
{% endblock %}