urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'vologda.views.home', name='home'),
    # url(r'^vologda/', include('vologda.foo.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),

    (r'^tinymce/', include('tinymce.urls')),

    url(r'^robots.txt$', 'django.views.static.serve', {'path':"/robots.txt",'document_root': settings.STATIC_ROOT, 'show_indexes': False }),
    url(r'^/?$', 'wlm.views.index_page'),
    url(r'^list/?$', 'wlm.views.list_page'),
    url(r'^list/region/(?P<id>[0-9]+)/?$', 'wlm.views.list_region'),
    url(r'^list/city/(?P<id>[0-9]+)/?$', 'wlm.views.list_city'),
    url(r'^upload/?$', 'wlm.views.upload'),
    url(r'^add/?$', 'wlm.views.add'),
    url(r'^monument/(?P<id>[0-9]+)/?$', 'wlm.views.monument'),
    url(r'^monument/(?P<id>[0-9]+)/photo/?$', 'wlm.views.monument_photo'),
    url(r'^monument/kult/(?P<kult_id>[0-9]+)/?$', 'wlm.views.redirect_by_kult_id'),
    url(r'^monument/edit/(?P<id>\d+)$', 'wlm.views.monument_edit_form'),
    url(r'^voting/?$', 'wlm.views.voting'),
    url(r'^vote/(?P<photo_id>\d+)/(?P<vote>\d+)/?$', 'wlm.views.vote_for_photo'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^ajax/markers/(?P<zoom>\d{1,2})/(?P<x_tile>\d+)/(?P<y_tile>\d+)/(?P<first>\d+)/(?P<last>\d+)$', 'wlm.ajax.get_tile_markers'),
    url(r'^ajax/markerscount/(?P<zoom>\d{1,2})/(?P<x_tile>\d+)/(?P<y_tile>\d+)$', 'wlm.ajax.get_tile_markers_count'),
    url(r'^ajax/markersregion/(?P<region>\d+)$', 'wlm.ajax.get_region_markers'),
    url(r'^ajax/markerscity/(?P<city>\d+)$', 'wlm.ajax.get_city_markers'),
    url(r'^ajax/citiesregion/(?P<region>\d+)$', 'wlm.ajax.get_region_cities'),

    url(r'^doubles$', 'wlm.views.coordinates_doubled'),
    url(r'^doubles/find$', 'wlm.views.monuments_double_coordinates'),
)

wlm/models.py
import os.path

from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User

from tinymce import models as tinymce_models


class Region(models.Model):
    ''' One region of RF'''
    class Meta():
        ordering = ['order']
        verbose_name = _("Region of RF")

    name = models.CharField(max_length=200)
    district = models.IntegerField(verbose_name=_("Federal district of RF"))
    order = models.IntegerField()
    latitude = models.FloatField(max_length=20, blank=True, null=True, verbose_name=_("Latitude"))
    longitude = models.FloatField(max_length=20, blank=True, null=True, verbose_name=_("Longitude"))
    scale = models.IntegerField(verbose_name=_("Scale"))
    gibdd_code = models.IntegerField(blank=True, default=0, verbose_name=_('GIBDD region code'))
    iso_code = models.CharField(max_length=6, blank=True, default='', verbose_name=_('ISO 3166-2 region code'))

    def __unicode__(self):
        return self.name


class City(models.Model):
    '''One RF city'''

    class Meta():
        ordering = ['name']
        verbose_name = _("City")

    region = models.ForeignKey(Region)
    name = models.CharField(max_length=200)
    latitude = models.FloatField(max_length=20, blank=True, null=True, verbose_name=_("Latitude"))
    longitude = models.FloatField(max_length=20, blank=True, null=True, verbose_name=_("Longitude"))
    capital = models.BooleanField(default=False, verbose_name=_("Capital"))

    def __unicode__(self):
        return "%s, %s" % (self.region.name, self.name)


class Street(models.Model):
    '''One city street'''
    region = models.ForeignKey(Region)
    city = models.ForeignKey(City)
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return "%s, %s, %s" % (self.region.name, self.city.name, self.name)


class Monument(models.Model):
    ''' Main class for working.
    This one contains complete definition for one building. It's a heart
    for application.
    '''
    STATE_CHOICES = (
        ('R', _("Restored")),
        ('S', _("Satisfactory")),
        ('U', _("Unsatisfactory")),
        ('A', _("Accident")),
    )

    PROTECTION_CHOICES = (
        ('F', _("Federal")),
        ('R', _("Regional")),
        ('L', _("Local")),
        ('D', _("Determined")),
        ('O', _("OPOKN")),
        ('N', _("No")),
    )
    TYPE_CHOICES = (
        ('C', _("Cultural")),
        ('A', _("Architectural")),
        ('H', _("Historical")),
        ('M', _("Monumental art")),
    )

    class Meta:
        permissions = (
            ('can_moderate', 'Can verify and change monument data'),
        )

    #minimal required fields
    # Geospatial
    region = models.ForeignKey(Region, verbose_name=_("Region of RF"))
    city = models.ForeignKey(City, verbose_name=_("City"), blank=True, null=True)
    street = models.ForeignKey(Street, verbose_name=_("Street"), blank=True, null=True)
    coord_lon = models.FloatField(max_length=20, blank=True, null=True, verbose_name=_("Longitude"))
    coord_lat = models.FloatField(max_length=20, blank=True, null=True, verbose_name=_("Latitude"))

    #Name and address
    name = models.CharField(max_length=250, blank=True, verbose_name=_("Name"))
    name_alt = models.CharField(max_length=250, blank=True, verbose_name=_("Alternative name"))
    address = models.CharField(max_length=250, blank=True, verbose_name=_("Address"))

    #Is this building a part of complex?
    complex_root = models.ForeignKey('self', blank=True, null=True, verbose_name=_("Belong to complex"))
    complex = models.BooleanField(default=False, verbose_name=_("Complex"))
    #Additional info, may be helpful during administration
    extra_info = tinymce_models.HTMLField(blank=True, verbose_name=_("Additional"))
    state = models.CharField(max_length=1, blank=True, choices=STATE_CHOICES, verbose_name=_("State"))
    protection = models.CharField(max_length=1, blank=True, choices=PROTECTION_CHOICES, verbose_name=_("Protection class"))
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, verbose_name=_("Type"))

    #External link to Wiki
    ruwiki = models.CharField(max_length=250, blank=True, verbose_name=_("Wikipedia article"))
    #External link to kulturnoe-nasledie.ru
    kult_id = models.BigIntegerField(blank=True, null=True, verbose_name=_("ID Kulturnoe Nasledie"))

    #Mark this true mean "We check all data"
    verified = models.BooleanField(default=False, verbose_name=_("Verified"))
    #End of minimal required fields

    def __unicode__(self):
        return "%s, %s" % (self.name, self.address)

    def show_name(self):
        return self.name or _("[Without name]")

    def show_wiki(self):
        return self.ruwiki


class MonumentPhoto(models.Model):
    def make_upload_folder(instance, filename):
        dir_name, image_name = os.path.split(filename)
        path = u"%d/%s" % (instance.monument.pk, image_name)
        return path

    monument = models.ForeignKey('Monument', verbose_name=_("Monument"))
    name = models.CharField(max_length=250, blank=True, verbose_name=_("Name"))
    commons_id = models.BigIntegerField(verbose_name=_("Image page ID"))
    author = models.CharField(max_length=250, blank=True, verbose_name=_("Author"))
    datetime = models.DateTimeField(auto_now=False, auto_now_add=False, verbose_name=_("Date & time"))
    contest_year = models.IntegerField(blank=True, null=True, verbose_name=_("Year of WLM contest"))
    folder = models.CharField(max_length=255, verbose_name=_('Commons folder'))
    width = models.IntegerField(verbose_name=_("File width"))
    height = models.IntegerField(verbose_name=_("File height"))
    size = models.IntegerField(verbose_name=_("File size"))

    def url_name(instance):
        return instance.name.replace(' ', '_')

    def __unicode__(self):
        return self.name


class MonumentPhotoRating(models.Model):
    user = models.ForeignKey(User, verbose_name=_("User ID"))
    photo = models.ForeignKey('MonumentPhoto', verbose_name=_("Photo"))
    vote = models.IntegerField(blank=True, null=True, verbose_name=_("Vote"))

    def __unicode__(self):
        return self.title

wlm/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from wlm.models import Monument, City


class MonumentForm(forms.ModelForm):
    class Meta:
        model = Monument
        widgets = {
            'coord_lat': forms.HiddenInput(),
            'coord_lon': forms.HiddenInput(),
            'extra_info': TinyMCE(),
        }

    def __init__(self, *args, **kwargs):
        super(MonumentForm, self).__init__(*args, **kwargs)
        qs = Monument.objects.filter(complex=True)
        self.fields['complex_root'].queryset = qs
        self.fields['city'].required = True

    def clean_street(self):
        return None

wlm/views.py
from django.db import connection
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import permission_required

from wlm.models import Region, City
from wlm.models import Monument, MonumentPhoto, MonumentPhotoRating
from wlm.forms import MonumentForm
from wlm.utils import get_region


MOSCOW_REGION_ID = '47'
MOSCOW_ID = '77'


def index_page(request):
    ip_region = get_region(request.META['REMOTE_ADDR'])
    if not ip_region:
        ip_region = MOSCOW_REGION_ID

    return render_to_response('wlm/index.html', {
        'region': Region.objects.values('id').get(gibdd_code=ip_region),
        'regions': Region.objects.values('id', 'name', 'latitude',
                    'longitude', 'scale').exclude(pk=MOSCOW_ID),
        'cities': City.objects.values('id', 'name').all(),
    }, context_instance=RequestContext(request))


def list_page(request):
    ip_region = get_region(request.META['REMOTE_ADDR'])
    if not ip_region:
        ip_region = MOSCOW_REGION_ID

    return render_to_response('wlm/list_index.html', {
        'region': Region.objects.values('id').get(gibdd_code=ip_region),
        'regions': Region.objects.values('id', 'name', 'latitude',
                    'longitude', 'scale').exclude(pk=MOSCOW_ID),
    }, context_instance=RequestContext(request))


def list_region(request, id):
    return render_to_response('wlm/list_region.html', {
        'region': Region.objects.get(pk=id),
        'cities': City.objects
                    .values('id', 'name', 'capital')
                    .filter(region_id=id)
                    .order_by('-capital', 'name'),
    }, context_instance=RequestContext(request))


def list_city(request, id):
    monuments = Monument.objects.filter(city_id=id, coord_lon__isnull=False,
                kult_id__isnull=False)
    return render_to_response('wlm/list_city.html', {
        'monuments': monuments,
        'city': City.objects.get(pk=id),
    }, context_instance=RequestContext(request))


def upload(request):
    m_list = Monument.objects.all()

    return render_to_response('wlm/upload.html', {
        'monuments_list': m_list,
    }, context_instance=RequestContext(request))


def add(request):
    m_list = Monument.objects.all()

    return render_to_response('wlm/add_monument.html', {
        'monuments_list': m_list,
    }, context_instance=RequestContext(request))


@permission_required('wlm.can_change')
def monument_edit_form(request, id):
    monument = Monument.objects.select_related().get(pk=id)
    form = MonumentForm(request.POST or None, instance=monument)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect('/monument/%s' % id)
    return render_to_response("wlm/edit_monument.html", {
        'id': id,
        'form': form,
    }, context_instance=RequestContext(request))


def monument(request, id):
    return render_to_response('wlm/monument.html', {
        'monument': get_object_or_404(Monument, pk=id),
    }, context_instance=RequestContext(request))


def monument_photo(request, id):
    return render_to_response('wlm/monument_photo.html', {
        'monument': get_object_or_404(Monument, pk=id),
    }, context_instance=RequestContext(request))


def redirect_by_kult_id(request, kult_id):
    m = get_object_or_404(Monument, kult_id=kult_id)
    return HttpResponseRedirect('/monument/%d' % m.id)


def coordinates_doubled(request):
    query = '''select count(id), coord_lat, coord_lon from wlm_monument
        group by coord_lat, coord_lon
        having count(id) > 1;'''
    cursor = connection.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    return render_to_response('coord_doubles.html', {'doubles': rows})


def monuments_double_coordinates(request):
    if request.GET['lat']:
        lat = float(request.GET.get('lat'))
    else:
        lat = None
    if request.GET['lon']:
        lon = float(request.GET.get('lon'))
    else:
        lon = None
    monuments = Monument.objects.filter(coord_lat=lat, coord_lon=lon)
    return render_to_response('wlm/monuments_double.html', {
        'monuments': monuments,
    })


def voting(request):
    if request.user is None or not request.user.is_active:
        return HttpResponseRedirect('/admin/')

    cnt = {}

    pr = MonumentPhotoRating.objects.all()
    pr2 = []
    for i in pr:
        pr2.append(i.photo_id)
    cnt = {
        'all': len(MonumentPhoto.objects.all()),
        'done': len(pr2),
    }

    p = MonumentPhoto.objects.exclude(id__in=pr2)
    if (len(p)):
        p = p.order_by('?')[0]
    else:
        return render_to_response('wlm/voting_over.html', {
            'cnt': cnt,
        }, context_instance=RequestContext(request))

    return render_to_response('wlm/voting.html', {
        'photo': p,
        'cnt': cnt,
    }, context_instance=RequestContext(request))


def vote_for_photo(request, photo_id, vote):
    vote = int(vote)
    if vote >= 1 and vote <= 5:
        r, created = MonumentPhotoRating.objects.get_or_create(
            user=request.user,
            photo=MonumentPhoto.objects.get(pk=photo_id))
        r.vote = vote
        r.save()
    return HttpResponseRedirect('/voting')

wlm/templates/wlm/add_monument.html
{% extends "base.html" %}

{% block title %}Добавить памятник — {% endblock %}

{% block content %}
<form>

<div class="row">
	<div class="span12">
		<fieldset class="form-horizontal">
			<div class="well control-group">
				<label class="control-label" for="p-name">Название:</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="p-name">
				</div>
			</div>
			<div class="well control-group">
				<label class="control-label" for="p-name">Автор:</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="p-name">
				</div>
			</div>
			<div class="well control-group">
				<label class="control-label" for="p-name">Год:</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="p-name">
				</div>
			</div>
			<div class="well control-group">
				<label class="control-label" for="p-file">Текст:</label>
				<div class="controls">
					<textarea class="input-xlarge" id="textarea" rows="3"></textarea>
				</div>
			</div>
			<div class="well control-group">
				<label class="control-label" for="p-file">Изображение:</label>
				<div class="controls">
					<input class="input-file" id="p-file" type="file">
				</div>
			</div>
		</fieldset>
	</div>
</div>

<div class="row">
<div class="span12">
<div class="well">
	<div class="span2">
		<div class="btn-group">
			<a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
				Регион
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
			{% for region in regions %}
				<li><a href="#" data-id="{{ region.id }}" data-coord="{{ region.long }},{{ region.lat }}">{{ region.name }}</a></li>
			{% endfor %}
			</ul>
		</div>
		<br />
		<div class="btn-group">
			<a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
				Город
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
			{% for region in regions %}
				<li><a href="#" data-id="{{ region.id }}" data-coord="{{ region.long }},{{ region.lat }}">{{ region.name }}</a></li>
			{% endfor %}
			</ul>
		</div>
		<br />
		<div class="btn-group">
			<a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
				Улица
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
			{% for region in regions %}
				<li><a href="#" data-id="{{ region.id }}" data-coord="{{ region.long }},{{ region.lat }}">{{ region.name }}</a></li>
			{% endfor %}
			</ul>
		</div>
	</div>

	<div class="span9">
		<div class="controls">
			<div class="input-append">
				<input class="span7" id="appendedInputButtons" size="16" type="text"><button class="btn pull-right" type="button"><i class="icon-search"></i> Найти памятник</button>
			</div>
		</div>

		<div id="map" class="map map-big"></div>
		<script type="text/javascript">
			var cmUrl = 'http://{s}.tile.cloudmade.com/{{ CMADE_KEY }}/997/256/{z}/{x}/{y}.png';
			var cmAttr = 'карта &copy; OpenStreetMap, рендер &copy; CloudMade';
			var map = new L.Map('map');
			map
				.setView(new L.LatLng(66, 94), 3)
				.addLayer(new L.TileLayer(cmUrl, { maxZoom: 18, attribution: cmAttr }));
			var clusterer = new LeafClusterer(map);

		{% for m in monuments_list %}
			{% if m.coord_lat %}
				clusterer.addMarker(new L.Marker(new L.LatLng({{ m.coord_lat|stringformat:"f" }}, {{ m.coord_lon|stringformat:"f" }})).bindPopup('<p><a href="/monument/{{ m.id }}">{{ m.street.name }}, {{ m.number }}</p>'));
			{% endif %}
		{% endfor %}
		</script>
	</div>
	<div style="clear:both"></div>
</div>
</div>
</div>

<div class="row">
	<div class="span12">
		<div class="form-actions">
			<button type="submit" class="btn btn-large btn-primary pull-right">Отправить</button>
		</div>
	</dev>
</div>

</form>
{% endblock %}

wlm/templates/wlm/edit_monument.html
{% extends "base.html" %}

{% block head %}
{{ form.media }}
{% endblock %}


{% block moderator_menu %}
<li class="pull-right"><a href="/admin/logout/">Выйти ({{ user }})</a></li>
<li class="pull-right"><a href="/monument/{{ id }}">Смотреть</a></li>
{% endblock %}


{% block content %}
<div class="row">
	<div id="main">
		<form class="form-horizontal" action="" method="post">
		<div class="span6">
			{% csrf_token %}
			{% for field in form.hidden_fields %}
				{{ field }}
			{% endfor %}
			<div class="control-group {% if form.name.errors %}error{% endif %}">
				<label class="control-label" for="id_name">{{ form.name.label }}</label>
				<div class="controls">
					{{ form.name }}
					{{ form.name.errors }}
				</div>
			</div>

			<div class="control-group {% if form.name_alt.errors %}error{% endif %}">
				<label class="control-label" for="id_name_alt">{{ form.name_alt.label }}</label>
				<div class="controls">
					{{ form.name_alt }}
					{{ form.name_alt.errors }}
				</div>
			</div>

			<div class="control-group {% if form.region.errors %}error{% endif %}">
				<label class="control-label" for="id_region">{{ form.region.label }}</label>
				<div class="controls">
					{{ form.region }}
					{{ form.region.errors }}
				</div>
			</div>

			<div class="control-group {% if form.city.errors %}error{% endif %}">
				<label class="control-label" for="id_city">{{ form.city.label }}</label>
				<div class="controls">
					{{ form.city }}
					{{ form.city.errors }}
				</div>
			</div>

			<div class="control-group {% if form.address.errors %}error{% endif %}">
				<label class="control-label" for="id_address">{{ form.address.label }}</label>
				<div class="controls">
					{{ form.address }}
					{{ form.address.errors }}
				</div>
			</div>

			<div class="control-group {% if form.extra_info.errors %}error{% endif %}">
				<label class="control-label" for="id_extra_info">{{ form.extra_info.label }}</label>
				<div class="controls">
					{{ form.extra_info }}
					{{ form.extra_info.errors }}
				</div>
			</div>

			<div class="control-group {% if form.complex_root.errors %}error{% endif %}">
				<label class="control-label" for="id_complex_root">{{ form.complex_root.label }}</label>
				<div class="controls">
					{{ form.complex_root }}
					{{ form.complex_root.errors }}
				</div>
			</div>

			<div class="control-group {% if form.complex.errors %}error{% endif %}">
				<label class="control-label" for="id_complex">{{ form.complex.label }}</label>
				<div class="controls">
					{{ form.complex }}
					{{ form.complex.errors }}
				</div>
			</div>

			<div class="control-group {% if form.kult_id.errors %}error{% endif %}">
				<label class="control-label" for="id_kult_id">{{ form.kult_id.label }}</label>
				<div class="controls">
					{{ form.kult_id }}
					{% if form.kult_id.value %}(<a target="_blank" href="http://kulturnoe-nasledie.ru/monuments.php?id={{ form.kult_id.value }}">открыть</a>){% endif %}
					{{ form.kult_id.errors }}
				</div>
			</div>

			<div class="control-group {% if form.ruwiki.errors %}error{% endif %}">
				<label class="control-label" for="id_ruwiki">{{ form.ruwiki.label }}</label>
				<div class="controls">
					{{ form.ruwiki }}
					{% if form.ruwiki.value %}(<a target="_blank" href="//ru.wikipedia.org/wiki/{{ form.ruwiki.value }}">открыть</a>){% endif %}
					{{ form.ruwiki.errors }}
				</div>
			</div>

			<div class="control-group {% if form.state.errors %}error{% endif %}">
				<label class="control-label" for="id_state">{{ form.state.label }}</label>
				<div class="controls">
					{{ form.state }}
					{{ form.state.errors }}
				</div>
			</div>

			<div class="control-group {% if form.protection.errors %}error{% endif %}">
				<label class="control-label" for="id_protection">{{ form.protection.label }}</label>
				<div class="controls">
					{{ form.protection }}
					{{ form.protection.errors }}
				</div>
			</div>

			<div class="control-group {% if form.type.errors %}error{% endif %}">
				<label class="control-label" for="id_type">{{ form.type.label }}</label>
				<div class="controls">
					{{ form.type }}
					{{ form.type.errors }}
				</div>
			</div>

			<div class="control-group {% if form.verified.errors %}error{% endif %}">
				<label class="control-label label label-info" for="id_verified">{{ form.verified.label }}</label>
				<div class="controls">
					{{ form.verified }}
					{{ form.verified.errors }}
				</div>
			</div>
			<input type="submit" class="btn btn-success btn-large pull-right" value="Сохранить" />
		</div>
		</form>
	</div>

	<div class="span6">
		<div id='map' style="width:200; heigth:150" class="map leaflet-container leaflet-fade-anim"></div>
		<script type='text/javascript'>
$(function(){
	var lat = $('#id_coord_lat').val() || 66,
		lon = $('#id_coord_lon').val() || 94;
	WLM.map.initMap('map', {
		'coord_lat': lat,
		'coord_lon': lon,
		'zoom': 17
		});
	var marker = {
		"coord_lat": lat,
		"coord_lon": lon,
		"name": $('#id_name').val(),
		"draggable": true
	};
	var m = WLM.map.addMarker(marker);
	m.on('dragend', function(e){
		var llm = m.getLatLng();
		$('#id_coord_lat').val(llm.lat);
		$('#id_coord_lon').val(llm.lng);
	});

	var setCities = function(data){
		var city_id = $('#id_city').val();
		$('#id_city').empty();
		$('#id_city').append("<option></option>");
		$.each(data, function(key, value){
			$('#id_city').append($("<option></option>")
				.attr("value", value.id)
				.text(value.name)
				.prop('selected', value.id == city_id));
		});
	}
	WLM.getRegionCities($('#id_region option:selected').val(), setCities);
	$('#id_region').change(function(){
		WLM.getRegionCities($('option:selected', $(this)).val(), setCities);
	});
});
		</script>
	</div>
</div>
{% endblock %}

wlm/templates/wlm/markers.html
<!DOCTYPE html>
<html lang="ru">
<body>
{% for m in monuments %}
{{ m.name|default:'U' }}
{% endfor %}
</body>
</html>

wlm/templates/wlm/monument_photo.html
{% extends "base.html" %}

{% block title %}{{ monument.name }} ({{ monument.address }}) — {% endblock %}

{% block moderator_menu %}
{% if perms.monument.can_change %}
<li class="pull-right"><a href="/admin/logout/">Выйти ({{ user }})</a></li>
<li class="pull-right"><a href="/monument/edit/{{ monument.id }}">Редактировать</a></li>
{% endif %}
{% endblock %}

{% block content %}
<div itemscope itemtype="http://schema.org/LandmarksOrHistoricalBuildings">
	<div class="row">
		<div id="main">
			<div id="find" class="show-grid">
				<div class="span-bg span12">
					<h2><a itemprop="url" href="/monument/{{ monument.id }}">←</a> {{ monument.name }}</h2>
				</div>
			</div>
		</div>
	</div>

{% if monument.monumentphoto_set.count %}
	<hr />
	<div class="row m-photo-big">
		<div class="span12">
			<ul class="thumbnails">
			{% for p in monument.monumentphoto_set.all %}
				<li itemscope itemtype="http://schema.org/Photograph" class="span3">
					<a itemprop="url" class="thumbnail" target="_blank" href="//commons.wikimedia.org/wiki/File:{{ p.url_name }}"><img itemprop="thumbnailUrl"
					{% if p.width <= 300 %}
						src="//upload.wikimedia.org/wikipedia/commons/{{ p.folder }}/{{ p.url_name }}"
					{% else %}
						src="//upload.wikimedia.org/wikipedia/commons/thumb/{{ p.folder }}/{{ p.url_name }}/{% if p.url_name|lower|slice:'-4:' == '.tif' %}lossy-page1-300px-{{ p.url_name }}.jpg{% else %}300px-{{ p.url_name }}{% endif %}"
					{% endif %}
						alt="{{ p.name }}, автор: {{ p.author }}" /></a>
					<p>Автор: <a itemprop="author" href="//commons.wikimedia.org/wiki/User:{{ p.author }}">{{ p.author }}</a></p>
				</li>
			{% endfor %}
			</ul>
		</div>
	</div>
{% endif %}
</div>
{% endblock %}